apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 3000   # External port clients will use
    targetPort: 3000 # Port your container is listening on
  type: NodePort
